---
- name: Install system-wide pip
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - python-pip

- name: Install system-wide supervisord from PyPI
  sudo: yes
  pip:
    executable: "{{ supervisord_pip_path }}"
    requirements: "{{ item }}"
    state: present
    # see http://supervisord.org/installing.html#installing-via-pip
    extra_args="--pre"
  with_items:
    - supervisor
